### ISSUE TITLE
Deprecate fern prefix for metadata properties

### ISSUE THREAD

**Issue by razor-x** [seamapi/nextlove#143]
We want to remove all references to fern from this repo, but that would be a breaking change and we need to update any downstream dependencies first to use different properties. So for this issue, we need to keep any fern properties and only introduce the new logic. I'm mostly looking at `sdkReturnValue` mapped to `x-fern-sdk-return-value` as an outlier.

For the other fern properties, looking at them they are all already handled by yaml frontmatter and/or blueprint in some way:

- `x-fern-ignore` is `undocumented` 
- `x-fern-sdk-method-name` is preferredMethod
- `x-fern-sdk-group-name` is route

So 

1. Deprecate `sdkReturnValue` and use yaml front matter instead: if `response_key` exists in yaml front matter, use it over `sdkReturnValue` to populate `x-fern-sdk-return-value`. Really, `response_key` should not be something considered in this project since it's a specific Seam API design choice to have a single resource as the main response, but we need to support the fern properties.
2. Use `undocumented` to populate `x-fern-ignore` (ok, actually not sure if this is correct, [what is this logic actually doing](https://github.com/seamapi/nextlove/blob/a3656421029c1b40eeaf4f6d44076aed77bc9f91/packages/nextlove/src/generators/generate-openapi/fern-sdk-utils.ts#L32)? What should determine if the endpoint is ignored?)

**Comment by andrii-balitskyi** [comment]
@razor-x I think you mentioned during our docs meeting that you'd provide some instructions here. Could you give me more details? We want to somehow mark the fern prefixes deprecated and add seam associated flags as a replacement?

**Comment by razor-x** [comment]
@andrii-balitskyi updated!

**Comment by andrii-balitskyi** [comment]
> (ok, actually not sure if this is correct, [what is this logic actually doing](https://github.com/seamapi/nextlove/blob/a3656421029c1b40eeaf4f6d44076aed77bc9f91/packages/nextlove/src/generators/generate-openapi/fern-sdk-utils.ts#L32)? What should determine if the endpoint is ignored?)

@razor-x I'm not sure what it does. Seems like it adds the ignore flag if an endpoint consists of a single path part like just `/resources` or something. But I don't think we have any endpoints like that as it contradicts our API design principles. 
We usually have `/resources/do_something`. Probably @itelo knows better as it seems that he wrote that code.

On as a separate related note regarding ignoring endpoints, we also have `excludeFromOpenApi` param that you can pass to the route spec, which will make openapi spec generator leave the endpoint out of the openapi spec completely (not just mark it as ignored). Apparently, this param hasn't made it's way to the [type annotation](https://github.com/seamapi/nextlove/blob/52cb997eb0abd05f3c32e9cdb2edb952e906715c/packages/nextlove/src/types/index.ts#L30-L45) of the route spec but it actually works and is used in a dozen of endpoints on seam-connect [[example](https://github.com/seamapi/seam-connect/blob/b4e30b360581b974b281a222c2c123421435ea47/pages/api/public/acs/access_groups/create.ts#L21)].
Should `excludeFromOpenApi` be removed and instead include the endpoints in the openapi spec and mark them `undocumented`?

**Comment by andrii-balitskyi** [comment]
Also, we keep using fern for generating our GO SDK. So, does it make sense to remove all references to fern from this repo in the first place?

**Comment by razor-x** [comment]
> Also, we keep using fern for generating our GO SDK. So, does it make sense to remove all references to fern from this repo in the first place?

We won't remove the fern properties until we understand how they are used downstream, but it doesn't really make sense for this project to understand fern concepts.

**Comment by razor-x** [comment]
So, `excludeFromOpenApi` might be useful, but I don't actually know why we would need it if we have `undocumented` (and `x-fern-ignore` using `undocumented`). Everything under `/public` is safe to include in the openapi spec and useful since often those endpoints are tested in beta before released. The only risk is that users consume the openapi spec and use undocumented endpoints, but that is not a concern IMO.

**Comment by razor-x** [comment]
In terms of what to do, I'd say leave `excludeFromOpenApi` for now, but we will stop using it for public routes. Otherwise 1 and 2 on this issue still looks correct. If we have any issues, they will be isolated to the Go SDK and we can deal with then.
