### ISSUE TITLE
Installing `nsm` binary assumes packages installed in sub-directory

### ISSUE THREAD

**Issue by canadaduane** [seamapi/nextlove#31]
The package.json file includes an `nsm` binary which is from this package's 'nextjs-server-modules' dependency:

```json
  "bin": {
    "nsm": "node_modules/nextjs-server-modules/bin.js",
    "nextlove": "bin.js"
  }
```
https://github.com/seamapi/nextlove/blob/main/packages/nextlove/package.json#L14

This pattern is not optimal, as it assumes packages are always placed in sub-directories; however, optimizing package managers like `pnpm` only support this with a flag (and it makes `pnpm` slower).

When used in its default way, `pnpm` reports the following error:

> WARN  Failed to create bin at /home/duane/Seam/seamos-backend/node_modules/.bin/nsm. The source file at /home/duane/Seam/seamos-backend/node_modules/nextlove/node_modules/nextjs-server-modules/bin.js does not exist.

**Comment by seveibar** [comment]
this should be easy to fix, we could introduce a `require("./nsm-bin.js")` and...

```javascript
#!/usr/bin/env node
require("nextjs-server-modules/bin.js")
```
