### ISSUE TITLE
Yarn build fails on Windows

### ISSUE THREAD

**Issue by EduardoFazolo** [seamapi/nextlove#32]
I wrote a more generic title because there are 2 main reasons for that:

### First reason is that the build command on `package.json` is using `cp`:
```json
"build": "rimraf dist && nsm build && tsup ./index.ts --dts --sourcemap && cp -r .next dist/.next",
```
Which is not a command on windows. There are many ways to solve this, but if a solution without any extra packages is required, then there probably should be a `build-windows` command, like:
```json
"build-windows": "rimraf dist && nsm build && tsup ./index.ts --dts --sourcemap && xcopy .next dist\\.next /e /i",
```
But that would affect other commands. So maybe there could be a discussion on what would be the best solution here.

### The second bug occurs in `parse-routes-in-package.ts`:
The line
```typescript
const fullPathGlob = path.join(packageDir, pathGlob)
```
returns an invalid path, at least on windows. It causes 
```typescript
const filepaths = await globby(`${fullPathGlob}`)
``` 
to return 0 filepaths. 

Globby docs recommend using `path.posix.join` instead:

![image](https://user-images.githubusercontent.com/22328692/215295088-2323390a-71d8-4f90-b2e6-80d2645d7eee.png)

So it'd be:
```typescript
// Load all route specs
  const fullPathGlob = path.posix.join(packageDir, pathGlob)
  console.log(`searching "${fullPathGlob}"...`)
  const filepaths = await globby(`${fullPathGlob}`)
  console.log(`found ${filepaths.length} files`)
```
And that worked for me.

I can attach a PR to this issue if necessary.

**Comment by codetheweb** [comment]
> First reason is that the build command on package.json is using cp:

Using a standard package for this is perfectly fine, maybe https://github.com/sindresorhus/cpy-cli?

> Globby docs recommend using path.posix.join instead:

This makes sense 👍.

> I can attach a PR to this issue if necessary.

A PR would be great! Thank you for looking into this.
