### ISSUE TITLE
Path params should be removed from queryParams type

### ISSUE THREAD

**Issue by itelo** [seamapi/nextlove#74]
![image](https://github.com/seamapi/nextlove/assets/11433064/1f0546f7-2e42-47d1-9015-54a0c9e60cc6)
![image](https://github.com/seamapi/nextlove/assets/11433064/563cdee8-282d-4c00-95b6-a80518db5033)

typescript should not complain since `organization_id` is already on the path

**Comment by codetheweb** [comment]
Duplicate of https://github.com/seamapi/nextlove/issues/62.
